name: miso

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "12.0"

settings:
  GCC_C_LANGUAGE_STANDARD: c11

targets:
  miso:
    type: library.dynamic
    platform: macOS
    sources:
        - path: assets/
          type: folder
        - path: deps/
          type: folder
        - path: tools
          type: folder
        - path: README.md
          type: folder
        - path: project.yml
          type: folder
        - path: Makefile
          type: folder
        - path: src/
    dependencies:
        - sdk: Cocoa.framework
        - sdk: Metal.framework
        - sdk: MetalKit.framework
        - sdk: Quartz.framework
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/deps]
        OTHER_CFLAGS: ["-x objective-c", -DSOKOL_METAL, -fobjc-arc, -DDEBUG]
  test:
    type: tool
    platform: macOS
    sources:
      - path: test.c
    dependencies:
      - target: miso
    settings:
        HEADER_SEARCH_PATHS: [$(PROJECT_DIR)/deps]
